### ISSUE TITLE
gist selected text

### ISSUE THREAD

**Issue by tj** [drudge/gist.chocmixin#2]
would be rad! I didnt see that as an option in the context menu, but it would be awesome!

**Comment by drudge** [comment]
Implemented in 7e4e07048f0b126b0a438b323d7a0215e063c900. You should be able to update from the Install Mixins window within Chocolat.

**Comment by tj** [comment]
hmm I entered my github credentials and it quit the app haha

**Comment by drudge** [comment]
Did it crash? If so, any crash log? Anything in Console.app? Reproducible ?

**Comment by tj** [comment]
oh bad creds i guess i dont even know my own password, but it throws and crashes the app:

```
12-11-09 8:13:29.219 PM [0x0-0x2dc2dc].com.chocolatapp.Chocolat:     at Request._callback (/Users/tj/Library/Application Support/Chocolat/Mixins/gist.chocmixin/node_modules/gister/gister.js:103:31)
12-11-09 8:13:29.219 PM [0x0-0x2dc2dc].com.chocolatapp.Chocolat:     at Request.request.self.callback (/Users/tj/Library/Application Support/Chocolat/Mixins/gist.chocmixin/node_modules/gister/node_modules/request/main.js:104:22)
12-11-09 8:13:29.219 PM [0x0-0x2dc2dc].com.chocolatapp.Chocolat:     at Request.<anonymous> (/Users/tj/Library/Application Support/Chocolat/Mixins/gist.chocmixin/node_modules/gister/node_modules/request/main.js:458:18)
12-11-09 8:13:29.219 PM [0x0-0x2dc2dc].com.chocolatapp.Chocolat:     at Request.EventEmitter.emit (events.js:88:17)
12-11-09 8:13:29.219 PM [0x0-0x2dc2dc].com.chocolatapp.Chocolat:     at IncomingMessage.Request.request.self.start.self.req.self.httpModule.request.buffer (/Users/tj/Library/Application Support/Chocolat/Mixins/gist.chocmixin/node_modules/gister/node_modules/request/main.js:423:16)
12-11-09 8:13:29.219 PM [0x0-0x2dc2dc].com.chocolatapp.Chocolat:     at IncomingMessage.EventEmitter.emit (events.js:115:20)
12-11-09 8:13:29.219 PM [0x0-0x2dc2dc].com.chocolatapp.Chocolat:     at IncomingMessage._emitEnd (http.js:366:10)
12-11-09 8:13:29.219 PM [0x0-0x2dc2dc].com.chocolatapp.Chocolat:     at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
```

**Comment by tj** [comment]
k it works now that i figured out my damn password hahaha.. pretty cool!

**Comment by drudge** [comment]
Oops. Nice catch, added error handling in 79d9dff39788ccdf0075999ebf9bc14ff9d3cb60. Again, should be updatable within the app.
